/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/world.glb --transform 
Files: public/world.glb [41.39MB] > /Applications/kanoa/lessons/youtube-tutorial-nextjs/dmeo-startup-app/world-transformed.glb [3.74MB] (91%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/world-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="world" scale={1.359}>
          <mesh name="ICO球" geometry={nodes.ICO球.geometry} material={materials.PaletteMaterial001} position={[0.711, -0.072, -0.311]} rotation={[1.433, -0.102, -2.032]} scale={[0.02, 0.02, 0.026]} />
          <mesh name="Roundcube001" geometry={nodes.Roundcube001.geometry} material={materials['マテリアル.008']} rotation={[-0.025, 0, 0]} scale={0.707} />
          <group name="Roundcube027" position={[0.505, 0.131, -0.532]} rotation={[0.139, -0.3, 1.791]} scale={0.736}>
            <mesh name="Roundcube018_1" geometry={nodes.Roundcube018_1.geometry} material={materials.PaletteMaterial002} />
            <mesh name="Roundcube018_2" geometry={nodes.Roundcube018_2.geometry} material={materials['マテリアル.012']} />
          </group>
          <mesh name="SEE_TEST" geometry={nodes.SEE_TEST.geometry} material={materials['see.001']} scale={0.736} />
          <mesh name="メタボール001" geometry={nodes.メタボール001.geometry} material={materials['マテリアル.030']} position={[0.25, -0.508, -0.547]} rotation={[2.114, -1.217, -1.824]} scale={0.018} />
          <mesh name="円柱005" geometry={nodes.円柱005.geometry} material={materials['マテリアル.019']} position={[0.688, 0.365, -0.264]} rotation={[-0.169, 0.261, -0.976]} scale={0.042} />
          <mesh name="円錐016" geometry={nodes.円錐016.geometry} material={materials['マテリアル.032']} position={[0.356, -0.57, 0.357]} rotation={[-2.026, 0.944, 0.059]} scale={0.736} />
          <mesh name="平面014" geometry={nodes.平面014.geometry} material={materials['マテリアル.029']} position={[0.149, -0.63, 0.468]} rotation={[-1.864, 0.203, 2.421]} scale={0.734} />
          <mesh name="立方体001" geometry={nodes.立方体001.geometry} material={materials['マテリアル.013']} position={[0, 0.739, 0.008]} scale={0.018} />
          <mesh name="立方体002" geometry={nodes.立方体002.geometry} material={materials['マテリアル.011']} position={[0, 0.739, 0.008]} scale={0.018} />
        </group>
        <group name="cloud" scale={2.076}>
          <group name="エンプティ" position={[-0.353, -0.022, 0.868]} rotation={[1.572, 0, 0.358]} scale={[0.104, 0.112, 0.211]}>
            <mesh name="Roundcube002" geometry={nodes.Roundcube002.geometry} material={materials.PaletteMaterial001} position={[0, -0.34, 0.685]} scale={[0.621, 0.575, 0.307]} />
          </group>
          <group name="エンプティ001" position={[-0.027, 0.691, 0.045]} scale={[0.108, 0.108, 0.237]}>
            <mesh name="Roundcube006" geometry={nodes.Roundcube006.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.389]} scale={[0.621, 0.791, 0.469]} />
          </group>
          <group name="エンプティ002" position={[-0.165, -0.162, -0.771]} rotation={[-1.807, 0, 0]} scale={[0.113, 0.113, 0.275]}>
            <mesh name="Roundcube010" geometry={nodes.Roundcube010.geometry} material={materials.PaletteMaterial001} position={[0.282, 0, 0.536]} rotation={[0, 1.571, 0]} scale={[0.374, 0.515, 0.622]} />
          </group>
          <group name="エンプティ003" position={[0.404, -0.53, -0.35]} rotation={[-2.867, -0.398, -0.671]} scale={[0.104, 0.112, 0.211]}>
            <mesh name="Roundcube014" geometry={nodes.Roundcube014.geometry} material={materials.PaletteMaterial001} position={[0, -0.34, 0.685]} scale={[0.621, 0.575, 0.307]} />
          </group>
          <group name="エンプティ027" position={[-0.701, -0.251, -1.706]} rotation={[-1.742, 0, 0.358]} scale={[0.104, 0.112, 0.211]}>
            <mesh name="Roundcube018" geometry={nodes.Roundcube018.geometry} material={materials.PaletteMaterial001} position={[0, -0.34, 0.685]} scale={[0.621, 0.575, 0.307]} />
          </group>
          <group name="エンプティ028" position={[-0.053, -1.367, 0.146]} rotation={[2.97, 0, 0]} scale={[0.108, 0.108, 0.237]}>
            <mesh name="Roundcube049" geometry={nodes.Roundcube049.geometry} material={materials.PaletteMaterial001} position={[0, 0, 0.389]} scale={[0.621, 0.791, 0.469]} />
          </group>
          <group name="エンプティ029" position={[-0.327, 0.578, 1.454]} rotation={[1.163, 0, 0]} scale={[0.113, 0.113, 0.275]}>
            <mesh name="Roundcube053" geometry={nodes.Roundcube053.geometry} material={materials.PaletteMaterial001} position={[0.282, 0, 0.536]} rotation={[0, 1.571, 0]} scale={[0.374, 0.515, 0.622]} />
          </group>
          <group name="エンプティ030" position={[0.802, 1.156, 0.505]} rotation={[0.103, -0.398, -0.671]} scale={[0.104, 0.112, 0.211]}>
            <mesh name="Roundcube057" geometry={nodes.Roundcube057.geometry} material={materials.PaletteMaterial001} position={[0, -0.34, 0.685]} scale={[0.621, 0.575, 0.307]} />
          </group>
        </group>
        <group name="hikouki" scale={3.943}>
          <group name="hikouki_" scale={0.614}>
            <group name="エンプティ010" position={[0, 0.58, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.049, 0.03]}>
              <group name="エンプティ009" position={[0, 0.643, -0.029]} scale={[0.505, 0.315, 0.505]}>
                <mesh name="円柱002" geometry={nodes.円柱002.geometry} material={materials.PaletteMaterial001} position={[0, -0.064, 0]} scale={1.209} />
              </group>
              <group name="エンプティ008" position={[-0.713, 0.021, 0.695]} scale={[0.269, 0.168, 0.269]}>
                <mesh name="円柱003" geometry={nodes.円柱003.geometry} material={materials.PaletteMaterial001} position={[0.601, 0, -0.498]} scale={1.197} />
              </group>
              <mesh name="Roundcube019" geometry={nodes.Roundcube019.geometry} material={materials.PaletteMaterial001} position={[0, 0.421, -0.029]} scale={[0.57, 0.356, 0.57]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/world-transformed.glb')
